"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-16 11:44:44.634890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('matched_rows', sa.Integer(), nullable=False),
    sa.Column('unresolved_rows', sa.Integer(), nullable=False),
    sa.Column('unmapped_columns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("kind IN ('stats','adp')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoring_preset', sa.String(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("scoring_preset IN ('standard','half_ppr','full_ppr')"),
    sa.CheckConstraint('id = 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('mfl_id', sa.Integer(), nullable=False),
    sa.Column('gsis_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('merge_name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('fantasypros_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.Integer(), nullable=True),
    sa.Column('yahoo_id', sa.String(), nullable=True),
    sa.Column('sleeper_id', sa.Integer(), nullable=True),
    sa.Column('cbs_id', sa.Integer(), nullable=True),
    sa.Column('pfr_id', sa.String(), nullable=True),
    sa.Column('fantasy_data_id', sa.Integer(), nullable=True),
    sa.Column('rotowire_id', sa.Integer(), nullable=True),
    sa.Column('nfl_id', sa.Integer(), nullable=True),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('db_season', sa.Integer(), nullable=True),
    sa.Column('seeded_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mfl_id')
    )
    op.create_index('idx_player_merge_team_pos', 'player', ['merge_name', 'team', 'position'], unique=False)
    op.create_index(op.f('ix_player_cbs_id'), 'player', ['cbs_id'], unique=False)
    op.create_index(op.f('ix_player_espn_id'), 'player', ['espn_id'], unique=False)
    op.create_index(op.f('ix_player_fantasy_data_id'), 'player', ['fantasy_data_id'], unique=False)
    op.create_index(op.f('ix_player_fantasypros_id'), 'player', ['fantasypros_id'], unique=False)
    op.create_index(op.f('ix_player_gsis_id'), 'player', ['gsis_id'], unique=True)
    op.create_index(op.f('ix_player_merge_name'), 'player', ['merge_name'], unique=False)
    op.create_index(op.f('ix_player_nfl_id'), 'player', ['nfl_id'], unique=False)
    op.create_index(op.f('ix_player_pfr_id'), 'player', ['pfr_id'], unique=False)
    op.create_index(op.f('ix_player_rotowire_id'), 'player', ['rotowire_id'], unique=False)
    op.create_index(op.f('ix_player_sleeper_id'), 'player', ['sleeper_id'], unique=False)
    op.create_index(op.f('ix_player_yahoo_id'), 'player', ['yahoo_id'], unique=False)
    op.create_table('source_column_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('mapping', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("strategy IN ('by_name','by_index','fantasypros_multi_header')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'position')
    )
    op.create_table('import_unresolved',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('csv_row', sa.Text(), nullable=False),
    sa.Column('parsed_name', sa.String(), nullable=True),
    sa.Column('parsed_team', sa.String(), nullable=True),
    sa.Column('resolved_player_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['resolved_player_id'], ['player.mfl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_adp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('adp_snake', sa.Float(), nullable=True),
    sa.Column('adp_auction', sa.Float(), nullable=True),
    sa.Column('ecr', sa.Float(), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.mfl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adp_player_latest', 'player_adp', ['player_id', sa.text('created_at DESC')], unique=False)
    op.create_table('player_distribution_params',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('fitted_at', sa.String(), nullable=False),
    sa.Column('historical_seasons', sa.String(), nullable=False),
    sa.Column('games_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.mfl_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_projection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.mfl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proj_player_latest', 'player_projection', ['player_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_proj_player_latest', table_name='player_projection')
    op.drop_table('player_projection')
    op.drop_table('player_distribution_params')
    op.drop_index('idx_adp_player_latest', table_name='player_adp')
    op.drop_table('player_adp')
    op.drop_table('import_unresolved')
    op.drop_table('source_column_mapping')
    op.drop_index(op.f('ix_player_yahoo_id'), table_name='player')
    op.drop_index(op.f('ix_player_sleeper_id'), table_name='player')
    op.drop_index(op.f('ix_player_rotowire_id'), table_name='player')
    op.drop_index(op.f('ix_player_pfr_id'), table_name='player')
    op.drop_index(op.f('ix_player_nfl_id'), table_name='player')
    op.drop_index(op.f('ix_player_merge_name'), table_name='player')
    op.drop_index(op.f('ix_player_gsis_id'), table_name='player')
    op.drop_index(op.f('ix_player_fantasypros_id'), table_name='player')
    op.drop_index(op.f('ix_player_fantasy_data_id'), table_name='player')
    op.drop_index(op.f('ix_player_espn_id'), table_name='player')
    op.drop_index(op.f('ix_player_cbs_id'), table_name='player')
    op.drop_index('idx_player_merge_team_pos', table_name='player')
    op.drop_table('player')
    op.drop_table('league_config')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
