# fly.toml app configuration file generated for mc-ff-sim-api on 2026-08-16T14:08:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mc-ff-sim-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'mc_ff_sim_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
